"""Verify every arXiv citation by fetching its record from the arXiv API.

For each candidate id in ``candidates.toml`` this script fetches
``https://export.arxiv.org/api/query?id_list=<id>`` and records the title,
authors, year and abstract URL that arXiv itself returns. A candidate whose
fetched title does not contain the expected title words is reported as a
MISMATCH and is not written to the BibTeX file. Nothing is cited unless it was
fetched successfully.

Run:  .venv\\Scripts\\python research\\literature\\verify_citations.py
Writes: research/literature/verified.json and research/literature/references.bib
"""

from __future__ import annotations

import json
import re
import sys
import time
import tomllib
import unicodedata
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

import httpx

HERE = Path(__file__).resolve().parent
ATOM = "{http://www.w3.org/2005/Atom}"
API = "https://export.arxiv.org/api/query"


def _norm(text: str) -> str:
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9 ]", " ", text.lower())


def _key_words(text: str) -> set[str]:
    stop = {"a", "an", "the", "of", "for", "and", "in", "on", "to", "with", "via", "is", "by", "from", "at", "as"}
    return {w for w in _norm(text).split() if len(w) > 2 and w not in stop}


def fetch_arxiv(client: httpx.Client, arxiv_id: str) -> dict:
    for attempt in range(4):
        r = client.get(API, params={"id_list": arxiv_id, "max_results": 1}, timeout=30)
        if r.status_code == 200:
            break
        time.sleep(5 * (attempt + 1))
    r.raise_for_status()
    root = ET.fromstring(r.text)
    entry = root.find(f"{ATOM}entry")
    if entry is None or entry.find(f"{ATOM}title") is None:
        raise RuntimeError(f"arXiv returned no entry for {arxiv_id}")
    title = " ".join(entry.findtext(f"{ATOM}title", "").split())
    if title.lower() == "error":
        raise RuntimeError(f"arXiv returned an error for {arxiv_id}: {entry.findtext(f'{ATOM}summary')}")
    authors = [" ".join(a.findtext(f"{ATOM}name", "").split()) for a in entry.findall(f"{ATOM}author")]
    published = entry.findtext(f"{ATOM}published", "")
    return {
        "id": arxiv_id,
        "title": title,
        "authors": authors,
        "year": int(published[:4]),
        "published": published,
        "url": f"https://arxiv.org/abs/{arxiv_id}",
    }


def _bib_escape(text: str) -> str:
    return text.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")


def bibtex(key: str, rec: dict) -> str:
    authors = " and ".join(rec["authors"])
    return (f"@misc{{{key},\n  title = {{{{{_bib_escape(rec['title'])}}}}},\n  author = {{{authors}}},\n"
            f"  year = {{{rec['year']}}},\n  eprint = {{{rec['id']}}},\n  archivePrefix = {{arXiv}},\n"
            f"  url = {{{rec['url']}}},\n  note = {{Verified against the arXiv API on {rec['verified_on']}}}\n}}\n")


def write_bib(verified: dict[str, dict], failures: list[str]) -> None:
    manual = tomllib.loads((HERE / "candidates.toml").read_text(encoding="utf-8")).get("web", {})
    web_path = HERE / "web_sources.json"
    fetched = json.loads(web_path.read_text(encoding="utf-8")) if web_path.exists() else {"web": {}}
    with (HERE / "references.bib").open("w", encoding="utf-8") as fh:
        fh.write("% Generated by verify_citations.py. Every entry was fetched and checked; do not edit by hand.\n\n")
        for key, rec in verified.items():
            fh.write(bibtex(key, rec) + "\n")
        for key, w in manual.items():
            check = fetched["web"].get(key)
            if not check or not check["matches"]:
                failures.append(f"{key}: web source not fetched or title mismatch; run fetch_web_sources.py")
                continue
            fh.write(f"@misc{{{key},\n  title = {{{{{_bib_escape(w['title'])}}}}},\n  author = {{{w['author']}}},\n"
                     f"  year = {{{w['year']}}},\n  howpublished = {{\\url{{{w['url']}}}}},\n"
                     f"  note = {{Fetched and checked on {fetched['fetched_on']}}}\n}}\n\n")


def main() -> int:
    if "--bib-only" in sys.argv:
        failures: list[str] = []
        write_bib(json.loads((HERE / "verified.json").read_text(encoding="utf-8")), failures)
        for f in failures:
            print(f, file=sys.stderr)
        return 1 if failures else 0
    candidates = tomllib.loads((HERE / "candidates.toml").read_text(encoding="utf-8"))["arxiv"]
    verified: dict[str, dict] = {}
    failures = []
    today = datetime.now(timezone.utc).date().isoformat()
    with httpx.Client(headers={"User-Agent": "jig-research-citation-check/0.1"}) as client:
        for key, cand in candidates.items():
            try:
                rec = fetch_arxiv(client, cand["id"])
            except Exception as exc:  # recorded and reported, never silently cited
                failures.append(f"{key}: FETCH FAILED {cand['id']}: {exc}")
                continue
            expected = _key_words(cand["expect"])
            got = _key_words(rec["title"])
            overlap = len(expected & got) / max(1, len(expected))
            if overlap < 0.6:
                failures.append(f"{key}: MISMATCH {cand['id']} expected {cand['expect']!r} got {rec['title']!r}")
                continue
            rec["verified_on"] = today
            rec["topic"] = cand.get("topic", "")
            verified[key] = rec
            print(f"ok   {key:22s} {rec['id']}  {rec['year']}  {rec['title'][:80]}")
            time.sleep(3.1)  # arXiv API etiquette: no more than one request every three seconds
    (HERE / "verified.json").write_text(json.dumps(verified, indent=1, ensure_ascii=False), encoding="utf-8")
    write_bib(verified, failures)
    for f in failures:
        print(f, file=sys.stderr)
    print(f"{len(verified)} verified, {len(failures)} failed")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
